language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt --use-mirrors
script:
    - mkdir -p remark
    - remarkable remark talk/a-brief-history-of-the-word.md remark
    - mv remark.html remark/index.html
after_success:
  - rm -rf remark
